# Generated by Django 4.1.1 on 2022-11-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='First_Name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='Last_Name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
