# Generated by Django 4.1.3 on 2022-11-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_first_name_profile_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='DOB',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
